# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd50d941e1ab61fb86c50f1c6d708fdd469a0d11f4905b83ee69fc439c3cb030f5c6e4f388a62bdabb65bcbd04b5db5757f9769d712ded154d7c70f9b2c8a59

test:
  secret_key_base: 79c494d88ebd21caf47eabac5ecb364c46d1b761c4ebf9f0ff73845fc313dce56e94860a3eecfc24b838d6a6e542c8ca3a3defae49012d4480acefb57497cda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
